export const FETCH_TEST_UPLOAD_REQUEST = 'FETCH_TEST_UPLOAD_REQUEST'
export const FETCH_TEST_UPLOAD_SUCCESS = 'FETCH_TEST_UPLOAD_SUCCESS'
export const FETCH_TEST_UPLOAD_FAILED = 'FETCH_TEST_UPLOAD_FAILED'
